### ISSUE TITLE
json2pc.py meets SIGSEGV

### ISSUE THREAD

**Issue by Ma-Weijian** [ChrisWu1997/DeepCAD#5]
Hi Chris.

Greetings.

DeepCAD is a really inspiring work and has shed light on future research such as parametric modeling. The results are promising and the code is clear.

However, every time when I tried to run json2pc.py, I always meet SIGSEGV halfway. The reported error is like 

`
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGSEGV(-11)}
`

I'm using ubuntu 20.04.3, with python 3.7.11 and pythonocc-core 7.5.1. I don't know whether it is the error my environment or something related to the raw CAD json data and I have little idea to debug.

Have you ever met this issue? If so, how did you fix it?

Thanks a lot.

**Comment by ChrisWu1997** [comment]
Yes, I also met this issue. It's caused by OpenCascade (pythonocc), which fails to create some CAD model from the json and throws out a segmentation fault. Sometimes it's a bit random.

My solution is to comment out the parallel execution code (line 77-79) and write a for loop to find out which data causes the problem (print out the data id during the loop). And then skip these data IDs in the next parallel run (see line 30 - 32).

**Comment by Ma-Weijian** [comment]
Thanks for the solution.
I used your method and fixed this issue.
